"""update_document_model_with_status_field

Revision ID: 20e0b9db090c
Revises: 1fa2cc95c28e
Create Date: 2025-06-14 02:02:32.831228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e0b9db090c'
down_revision = '1fa2cc95c28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###