"""add document model

Revision ID: 47abacc1105d
Revises: 3433b6c11700
Create Date: 2025-04-17 20:23:55.006001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47abacc1105d'
down_revision = '3433b6c11700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###