"""add_user_favorites_table

Revision ID: a694cc315a17
Revises: 47abacc1105d
Create Date: 2025-05-05 00:31:59.811494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a694cc315a17'
down_revision = '47abacc1105d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='unique_user_document_favorite')
    )
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorites_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorites_id'))

    op.drop_table('user_favorites')
    # ### end Alembic commands ###