// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_messages.sql

package repository

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages (session_id, content, role, created_at, message_metadata)
VALUES ($1, $2, $3, now(), $4)
RETURNING id, session_id, content, role, created_at, message_metadata
`

type CreateMessageParams struct {
	SessionID       *string `json:"session_id"`
	Content         string  `json:"content"`
	Role            string  `json:"role"`
	MessageMetadata []byte  `json:"message_metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SessionID,
		arg.Content,
		arg.Role,
		arg.MessageMetadata,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.Role,
		&i.CreatedAt,
		&i.MessageMetadata,
	)
	return i, err
}

const listMessagesBySessionID = `-- name: ListMessagesBySessionID :many
SELECT id, session_id, content, role, created_at, message_metadata
FROM chat_messages
WHERE session_id = $1
ORDER BY id
`

func (q *Queries) ListMessagesBySessionID(ctx context.Context, sessionID *string) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.Role,
			&i.CreatedAt,
			&i.MessageMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
