// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_sessions.sql

package repository

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO chat_sessions (id, user_id, title, document_ids, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, user_id, title, document_ids, created_at, updated_at, last_message
`

type CreateSessionParams struct {
	ID          string  `json:"id"`
	UserID      *int32  `json:"user_id"`
	Title       string  `json:"title"`
	DocumentIds []int32 `json:"document_ids"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.DocumentIds,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessage,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     string `json:"id"`
	UserID *int32 `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, title, document_ids, created_at, updated_at, last_message
FROM chat_sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessage,
	)
	return i, err
}

const getSessionByIDForUser = `-- name: GetSessionByIDForUser :one
SELECT id, user_id, title, document_ids, created_at, updated_at, last_message
FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type GetSessionByIDForUserParams struct {
	ID     string `json:"id"`
	UserID *int32 `json:"user_id"`
}

func (q *Queries) GetSessionByIDForUser(ctx context.Context, arg GetSessionByIDForUserParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getSessionByIDForUser, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessage,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, title, document_ids, created_at, updated_at, last_message
FROM chat_sessions
WHERE user_id = $1
ORDER BY updated_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID *int32) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.DocumentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastMessage = `-- name: UpdateSessionLastMessage :exec
UPDATE chat_sessions
SET last_message = $2,
    updated_at   = now()
WHERE id = $1
`

type UpdateSessionLastMessageParams struct {
	ID          string  `json:"id"`
	LastMessage *string `json:"last_message"`
}

func (q *Queries) UpdateSessionLastMessage(ctx context.Context, arg UpdateSessionLastMessageParams) error {
	_, err := q.db.Exec(ctx, updateSessionLastMessage, arg.ID, arg.LastMessage)
	return err
}
