// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package repository

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    filename, original_filename, file_path, file_type, file_size,
    processed, processing_error, user_id, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, filename, original_filename, file_path, file_type, file_size,
          upload_date, processed, processing_error, user_id, status
`

type CreateDocumentParams struct {
	Filename         *string `json:"filename"`
	OriginalFilename *string `json:"original_filename"`
	FilePath         *string `json:"file_path"`
	FileType         *string `json:"file_type"`
	FileSize         *string `json:"file_size"`
	Processed        *bool   `json:"processed"`
	ProcessingError  *string `json:"processing_error"`
	UserID           *int32  `json:"user_id"`
	Status           *string `json:"status"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Filename,
		arg.OriginalFilename,
		arg.FilePath,
		arg.FileType,
		arg.FileSize,
		arg.Processed,
		arg.ProcessingError,
		arg.UserID,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadDate,
		&i.Processed,
		&i.ProcessingError,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, filename, original_filename, file_path, file_type, file_size,
       upload_date, processed, processing_error, user_id, status
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id int32) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadDate,
		&i.Processed,
		&i.ProcessingError,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const listAllDocuments = `-- name: ListAllDocuments :many
SELECT id, filename, original_filename, file_path, file_type, file_size,
       upload_date, processed, processing_error, user_id, status
FROM documents
ORDER BY id
OFFSET $1
LIMIT $2
`

type ListAllDocumentsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listAllDocuments, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.UploadDate,
			&i.Processed,
			&i.ProcessingError,
			&i.UserID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, filename, original_filename, file_path, file_type, file_size,
       upload_date, processed, processing_error, user_id, status
FROM documents
WHERE user_id = $1
ORDER BY id
OFFSET $2
LIMIT $3
`

type ListDocumentsByUserParams struct {
	UserID *int32 `json:"user_id"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListDocumentsByUser(ctx context.Context, arg ListDocumentsByUserParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.UploadDate,
			&i.Processed,
			&i.ProcessingError,
			&i.UserID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status           = $2,
    processed        = $3,
    processing_error = $4
WHERE id = $1
RETURNING id, filename, original_filename, file_path, file_type, file_size,
          upload_date, processed, processing_error, user_id, status
`

type UpdateDocumentStatusParams struct {
	ID              int32   `json:"id"`
	Status          *string `json:"status"`
	Processed       *bool   `json:"processed"`
	ProcessingError *string `json:"processing_error"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus,
		arg.ID,
		arg.Status,
		arg.Processed,
		arg.ProcessingError,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalFilename,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadDate,
		&i.Processed,
		&i.ProcessingError,
		&i.UserID,
		&i.Status,
	)
	return i, err
}
