// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extractions.sql

package repository

import (
	"context"
)

const deleteExtractionsByDocumentID = `-- name: DeleteExtractionsByDocumentID :exec
DELETE FROM extractions WHERE document_id = $1
`

func (q *Queries) DeleteExtractionsByDocumentID(ctx context.Context, documentID int32) error {
	_, err := q.db.Exec(ctx, deleteExtractionsByDocumentID, documentID)
	return err
}

const getExtractionByDocumentID = `-- name: GetExtractionByDocumentID :one
SELECT id, document_id, content, extraction_date, status, error
FROM extractions
WHERE document_id = $1
`

func (q *Queries) GetExtractionByDocumentID(ctx context.Context, documentID int32) (Extraction, error) {
	row := q.db.QueryRow(ctx, getExtractionByDocumentID, documentID)
	var i Extraction
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.ExtractionDate,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const upsertExtraction = `-- name: UpsertExtraction :one
INSERT INTO extractions (document_id, content, extraction_date, status, error)
VALUES ($1, $2, now(), $3, $4)
RETURNING id, document_id, content, extraction_date, status, error
`

type UpsertExtractionParams struct {
	DocumentID int32   `json:"document_id"`
	Content    []byte  `json:"content"`
	Status     *string `json:"status"`
	Error      *string `json:"error"`
}

// Insert or replace the extraction row for a document. There is no unique
// constraint on document_id in the base schema, so we delete any existing row
// first (done in a tx by the caller) — this query performs the insert.
func (q *Queries) UpsertExtraction(ctx context.Context, arg UpsertExtractionParams) (Extraction, error) {
	row := q.db.QueryRow(ctx, upsertExtraction,
		arg.DocumentID,
		arg.Content,
		arg.Status,
		arg.Error,
	)
	var i Extraction
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Content,
		&i.ExtractionDate,
		&i.Status,
		&i.Error,
	)
	return i, err
}
