// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJobsByDocumentID = `-- name: CancelJobsByDocumentID :execrows
UPDATE processing_jobs
SET status     = 'cancelled',
    locked_at  = NULL,
    locked_by  = NULL,
    updated_at = now()
WHERE document_id = $1 AND status IN ('pending', 'running')
`

func (q *Queries) CancelJobsByDocumentID(ctx context.Context, documentID int32) (int64, error) {
	result, err := q.db.Exec(ctx, cancelJobsByDocumentID, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE processing_jobs
SET status     = 'running',
    locked_at  = now(),
    locked_by  = $1,
    attempt    = attempt + 1,
    updated_at = now()
WHERE id = (
    SELECT id FROM processing_jobs
    WHERE status = 'pending' AND run_after <= now()
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, document_id, status, stage, attempt, max_attempts, error,
          idempotency_key, locked_at, locked_by, run_after, created_at, updated_at
`

// Atomically claim the oldest due pending job for this worker.
func (q *Queries) ClaimNextJob(ctx context.Context, lockedBy *string) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, claimNextJob, lockedBy)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Stage,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.IdempotencyKey,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE processing_jobs
SET status     = 'completed',
    locked_at  = NULL,
    locked_by  = NULL,
    error      = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO processing_jobs (document_id, idempotency_key, status, stage)
VALUES ($1, $2, 'pending', 'extract')
ON CONFLICT (idempotency_key) DO UPDATE SET updated_at = processing_jobs.updated_at
RETURNING id, document_id, status, stage, attempt, max_attempts, error,
          idempotency_key, locked_at, locked_by, run_after, created_at, updated_at
`

type EnqueueJobParams struct {
	DocumentID     int32  `json:"document_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

// Insert a pending job for a document. The idempotency_key ("doc:{id}") makes
// re-enqueue a no-op: on conflict we return the existing row instead of a dup.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, enqueueJob, arg.DocumentID, arg.IdempotencyKey)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Stage,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.IdempotencyKey,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE processing_jobs
SET status     = 'failed',
    locked_at  = NULL,
    locked_by  = NULL,
    error      = $2,
    updated_at = now()
WHERE id = $1
`

type FailJobParams struct {
	ID    int64   `json:"id"`
	Error *string `json:"error"`
}

// Terminal failure (no attempts remaining).
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.Error)
	return err
}

const getJobByDocumentID = `-- name: GetJobByDocumentID :one
SELECT id, document_id, status, stage, attempt, max_attempts, error,
       idempotency_key, locked_at, locked_by, run_after, created_at, updated_at
FROM processing_jobs
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetJobByDocumentID(ctx context.Context, documentID int32) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, getJobByDocumentID, documentID)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Stage,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Error,
		&i.IdempotencyKey,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimStaleJobs = `-- name: ReclaimStaleJobs :execrows
UPDATE processing_jobs
SET status     = 'pending',
    locked_at  = NULL,
    locked_by  = NULL,
    updated_at = now()
WHERE status = 'running' AND locked_at < $1
`

// Reset jobs whose worker died (locked_at older than the visibility timeout)
// back to pending so another worker can claim them.
func (q *Queries) ReclaimStaleJobs(ctx context.Context, lockedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleJobs, lockedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :exec
UPDATE processing_jobs
SET status     = 'pending',
    locked_at  = NULL,
    locked_by  = NULL,
    error      = $2,
    run_after  = $3,
    updated_at = now()
WHERE id = $1
`

type RetryJobParams struct {
	ID       int64              `json:"id"`
	Error    *string            `json:"error"`
	RunAfter pgtype.Timestamptz `json:"run_after"`
}

// Return a failed attempt to the queue with a delayed run_after (backoff).
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.ID, arg.Error, arg.RunAfter)
	return err
}
