// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID              int32            `json:"id"`
	SessionID       *string          `json:"session_id"`
	Content         string           `json:"content"`
	Role            string           `json:"role"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	MessageMetadata []byte           `json:"message_metadata"`
}

type ChatSession struct {
	ID          string           `json:"id"`
	UserID      *int32           `json:"user_id"`
	Title       string           `json:"title"`
	DocumentIds []int32          `json:"document_ids"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	LastMessage *string          `json:"last_message"`
}

type Document struct {
	ID               int32              `json:"id"`
	Filename         *string            `json:"filename"`
	OriginalFilename *string            `json:"original_filename"`
	FilePath         *string            `json:"file_path"`
	FileType         *string            `json:"file_type"`
	FileSize         *string            `json:"file_size"`
	UploadDate       pgtype.Timestamptz `json:"upload_date"`
	Processed        *bool              `json:"processed"`
	ProcessingError  *string            `json:"processing_error"`
	UserID           *int32             `json:"user_id"`
	Status           *string            `json:"status"`
}

type Extraction struct {
	ID             int32            `json:"id"`
	DocumentID     int32            `json:"document_id"`
	Content        []byte           `json:"content"`
	ExtractionDate pgtype.Timestamp `json:"extraction_date"`
	Status         *string          `json:"status"`
	Error          *string          `json:"error"`
}

type ProcessingJob struct {
	ID             int64              `json:"id"`
	DocumentID     int32              `json:"document_id"`
	Status         string             `json:"status"`
	Stage          string             `json:"stage"`
	Attempt        int32              `json:"attempt"`
	MaxAttempts    int32              `json:"max_attempts"`
	Error          *string            `json:"error"`
	IdempotencyKey string             `json:"idempotency_key"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LockedBy       *string            `json:"locked_by"`
	RunAfter       pgtype.Timestamptz `json:"run_after"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        int32              `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   *bool              `json:"revoked"`
	UserID    int32              `json:"user_id"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *string            `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TablesMetadatum struct {
	ID             int32            `json:"id"`
	TableID        *string          `json:"table_id"`
	TableName      *string          `json:"table_name"`
	DocumentID     *int32           `json:"document_id"`
	PageNumber     *int32           `json:"page_number"`
	ExtractionDate pgtype.Timestamp `json:"extraction_date"`
	Status         *string          `json:"status"`
}

type User struct {
	ID             int32              `json:"id"`
	Email          string             `json:"email"`
	Username       string             `json:"username"`
	HashedPassword string             `json:"hashed_password"`
	FirstName      *string            `json:"first_name"`
	LastName       *string            `json:"last_name"`
	IsActive       *bool              `json:"is_active"`
	IsSuperuser    *bool              `json:"is_superuser"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserFavorite struct {
	ID         int32 `json:"id"`
	UserID     int32 `json:"user_id"`
	DocumentID int32 `json:"document_id"`
}

type VectorEntry struct {
	ID              int32            `json:"id"`
	DocumentID      *int32           `json:"document_id"`
	ChunkText       string           `json:"chunk_text"`
	MessageMetadata []byte           `json:"message_metadata"`
	PageNumber      *int32           `json:"page_number"`
	Vector          *string          `json:"vector"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}
