// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, expires_at, user_id, user_agent, ip_address, revoked)
VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, token, expires_at, revoked, user_id, user_agent, ip_address, created_at
`

type CreateRefreshTokenParams struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserID    int32              `json:"user_id"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *string            `json:"ip_address"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.Token,
		arg.ExpiresAt,
		arg.UserID,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getValidRefreshToken = `-- name: GetValidRefreshToken :one
SELECT id, token, expires_at, revoked, user_id, user_agent, ip_address, created_at
FROM refresh_tokens
WHERE token = $1
  AND revoked = false
  AND expires_at > now()
`

func (q *Queries) GetValidRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getValidRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked = true
WHERE user_id = $1
  AND revoked = false
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked = true
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
