// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables_metadata.sql

package repository

import (
	"context"
)

const listTableMetadataByDocument = `-- name: ListTableMetadataByDocument :many
SELECT id, table_id, table_name, document_id, page_number, extraction_date, status
FROM tables_metadata
WHERE document_id = $1
ORDER BY page_number
`

func (q *Queries) ListTableMetadataByDocument(ctx context.Context, documentID *int32) ([]TablesMetadatum, error) {
	rows, err := q.db.Query(ctx, listTableMetadataByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TablesMetadatum
	for rows.Next() {
		var i TablesMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.TableName,
			&i.DocumentID,
			&i.PageNumber,
			&i.ExtractionDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTableMetadata = `-- name: UpsertTableMetadata :exec
INSERT INTO tables_metadata (table_id, table_name, document_id, page_number, extraction_date, status)
VALUES ($1, $2, $3, $4, now(), $5)
ON CONFLICT (table_id) DO UPDATE
SET table_name      = EXCLUDED.table_name,
    document_id     = EXCLUDED.document_id,
    page_number     = EXCLUDED.page_number,
    extraction_date = now(),
    status          = EXCLUDED.status
`

type UpsertTableMetadataParams struct {
	TableID    *string `json:"table_id"`
	TableName  *string `json:"table_name"`
	DocumentID *int32  `json:"document_id"`
	PageNumber *int32  `json:"page_number"`
	Status     *string `json:"status"`
}

// Records (or refreshes) one dynamic extraction table's metadata. table_id is
// the unique full table name produced by md2sql.
func (q *Queries) UpsertTableMetadata(ctx context.Context, arg UpsertTableMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertTableMetadata,
		arg.TableID,
		arg.TableName,
		arg.DocumentID,
		arg.PageNumber,
		arg.Status,
	)
	return err
}
