// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_favorites.sql

package repository

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO user_favorites (user_id, document_id)
VALUES ($1, $2)
ON CONFLICT ON CONSTRAINT unique_user_document_favorite DO NOTHING
`

type AddFavoriteParams struct {
	UserID     int32 `json:"user_id"`
	DocumentID int32 `json:"document_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.DocumentID)
	return err
}

const favoriteExists = `-- name: FavoriteExists :one
SELECT EXISTS (
    SELECT 1 FROM user_favorites
    WHERE user_id = $1 AND document_id = $2
)
`

type FavoriteExistsParams struct {
	UserID     int32 `json:"user_id"`
	DocumentID int32 `json:"document_id"`
}

func (q *Queries) FavoriteExists(ctx context.Context, arg FavoriteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, favoriteExists, arg.UserID, arg.DocumentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoriteDocuments = `-- name: ListFavoriteDocuments :many
SELECT d.id, d.filename, d.original_filename, d.file_path, d.file_type, d.file_size,
       d.upload_date, d.processed, d.processing_error, d.user_id, d.status
FROM documents d
JOIN user_favorites uf ON uf.document_id = d.id
WHERE uf.user_id = $1
ORDER BY d.id
`

func (q *Queries) ListFavoriteDocuments(ctx context.Context, userID int32) ([]Document, error) {
	rows, err := q.db.Query(ctx, listFavoriteDocuments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalFilename,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.UploadDate,
			&i.Processed,
			&i.ProcessingError,
			&i.UserID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :execrows
DELETE FROM user_favorites
WHERE user_id = $1 AND document_id = $2
`

type RemoveFavoriteParams struct {
	UserID     int32 `json:"user_id"`
	DocumentID int32 `json:"document_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
