// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vector_entries.sql

package repository

import (
	"context"
)

const countVectorEntriesByDocumentID = `-- name: CountVectorEntriesByDocumentID :one
SELECT COUNT(*) FROM vector_entries WHERE document_id = $1
`

func (q *Queries) CountVectorEntriesByDocumentID(ctx context.Context, documentID *int32) (int64, error) {
	row := q.db.QueryRow(ctx, countVectorEntriesByDocumentID, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVectorEntriesByDocumentID = `-- name: DeleteVectorEntriesByDocumentID :exec
DELETE FROM vector_entries WHERE document_id = $1
`

func (q *Queries) DeleteVectorEntriesByDocumentID(ctx context.Context, documentID *int32) error {
	_, err := q.db.Exec(ctx, deleteVectorEntriesByDocumentID, documentID)
	return err
}

const insertVectorEntry = `-- name: InsertVectorEntry :one
INSERT INTO vector_entries (document_id, chunk_text, message_metadata, page_number, vector, created_at)
VALUES ($1, $2, $3, $4, NULL, now())
RETURNING id, document_id, chunk_text, message_metadata, page_number, vector, created_at
`

type InsertVectorEntryParams struct {
	DocumentID      *int32 `json:"document_id"`
	ChunkText       string `json:"chunk_text"`
	MessageMetadata []byte `json:"message_metadata"`
	PageNumber      *int32 `json:"page_number"`
}

func (q *Queries) InsertVectorEntry(ctx context.Context, arg InsertVectorEntryParams) (VectorEntry, error) {
	row := q.db.QueryRow(ctx, insertVectorEntry,
		arg.DocumentID,
		arg.ChunkText,
		arg.MessageMetadata,
		arg.PageNumber,
	)
	var i VectorEntry
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkText,
		&i.MessageMetadata,
		&i.PageNumber,
		&i.Vector,
		&i.CreatedAt,
	)
	return i, err
}

const listVectorEntries = `-- name: ListVectorEntries :many
SELECT id, document_id, chunk_text, message_metadata, page_number, vector, created_at
FROM vector_entries
ORDER BY id
`

// All chunks (used when no document filter is supplied).
func (q *Queries) ListVectorEntries(ctx context.Context) ([]VectorEntry, error) {
	rows, err := q.db.Query(ctx, listVectorEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorEntry
	for rows.Next() {
		var i VectorEntry
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkText,
			&i.MessageMetadata,
			&i.PageNumber,
			&i.Vector,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVectorEntriesByDocumentIDs = `-- name: ListVectorEntriesByDocumentIDs :many
SELECT id, document_id, chunk_text, message_metadata, page_number, vector, created_at
FROM vector_entries
WHERE document_id = ANY($1::int[])
ORDER BY id
`

// Chunks restricted to the given document ids (RAG retrieval with a filter).
func (q *Queries) ListVectorEntriesByDocumentIDs(ctx context.Context, documentIds []int32) ([]VectorEntry, error) {
	rows, err := q.db.Query(ctx, listVectorEntriesByDocumentIDs, documentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorEntry
	for rows.Next() {
		var i VectorEntry
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkText,
			&i.MessageMetadata,
			&i.PageNumber,
			&i.Vector,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
